packages:
  - app/
  - backend/*
  - packages/*
  - '!**/test/**'

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@prisma/client'
  - '@prisma/engines'
  - bcrypt
  - core-js
  - esbuild
  - mediasoup
  - prisma
  - vue-demi
